import { Open_Sans } from "next/font/google"; // Import Open Sans from next/font
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

// Configure Open Sans with the desired weights
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["400", "600", "700"], // Add the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`} // Use Open Sans
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
